---
roles:
  - name: sshd_configuration
    scm: git
    src: https://github.com/tiny-company/asbl-sshd_configuration.git
    version: main  

  - name: apt_packages_install
    scm: git
    src: git@github.com:tiny-company/asbl-apt_packages_install.git
    version: main  

collections:
  - name: scaleway.scaleway
  - name: community.general
  - name: ansible.posix