---

- name: Configure sshd playbook
  hosts: all
  roles:
    - role: sshd_configuration
      become: true
      become_user: "{{ sshd_configuration_user }}"
      tags: [sshd_configuration]
