---
# Description : Configure Motd for sshd
# file : _ssh_banner.yml

- name: configure banner for sshd
  template:
    src: issue.j2
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/issue
    - /etc/issue.net

- name: make sure custom banner is active in config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Banner'
    line: 'Banner /etc/issue.net'
    state: absent
  notify: restart sshd
