---
# Description : Configure ssh cipher (The algorithm(s) used for symmetric session encryption) according to version
# file : _crypto_ciphers.yml
# Source : https://github.com/dev-sec/ansible-ssh-hardening/blob/master/tasks/crypto_hostkeys.yml

- name: set ciphers according to openssh-version if openssh >= 5.3
  set_fact:
    ssh_ciphers: '{{ ssh_ciphers_53_default }}'
  when: sshd_version is version('5.3', '>=')

- name: set ciphers according to openssh-version if openssh >= 6.6
  set_fact:
    ssh_ciphers: '{{ ssh_ciphers_66_default }}'
  when: sshd_version is version('6.6', '>=')
